# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commands.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\"\x06\n\x04Void\"*\n\x15SupportedStreamsReply\x12\x11\n\tprotocols\x18\x01 \x03(\t\")\n\x15\x43\x61mStreamStartRequest\x12\x10\n\x08protocol\x18\x01 \x01(\t\"\x1d\n\rCamStreamPort\x12\x0c\n\x04port\x18\x01 \x01(\x05\"5\n\x0eGpsCoordinates\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x1f\n\rProcessorData\x12\x0e\n\x06status\x18\x01 \x01(\t\"!\n\x0b\x42\x61tteryData\x12\x12\n\npercentage\x18\x01 \x01(\x05\"&\n\x16GeneralInformationData\x12\x0c\n\x04info\x18\x01 \x01(\t2\x93\x03\n\x0f\x43ommandsService\x12\x19\n\tHeartbeat\x12\x05.Void\x1a\x05.Void\x12\x33\n\x12GetCameraProtocols\x12\x05.Void\x1a\x16.SupportedStreamsReply\x12\x35\n\x0bStartCamera\x12\x16.CamStreamStartRequest\x1a\x0e.CamStreamPort\x12#\n\nStopCamera\x12\x0e.CamStreamPort\x1a\x05.Void\x12\x18\n\x08ResetUdp\x12\x05.Void\x1a\x05.Void\x12+\n\x11GetGpsCoordinates\x12\x05.Void\x1a\x0f.GpsCoordinates\x12+\n\x12GetProcessorStatus\x12\x05.Void\x1a\x0e.ProcessorData\x12\'\n\x10GetBatteryStatus\x12\x05.Void\x1a\x0c.BatteryData\x12\x37\n\x15GetGeneralInformation\x12\x05.Void\x1a\x17.GeneralInformationDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=18
  _globals['_VOID']._serialized_end=24
  _globals['_SUPPORTEDSTREAMSREPLY']._serialized_start=26
  _globals['_SUPPORTEDSTREAMSREPLY']._serialized_end=68
  _globals['_CAMSTREAMSTARTREQUEST']._serialized_start=70
  _globals['_CAMSTREAMSTARTREQUEST']._serialized_end=111
  _globals['_CAMSTREAMPORT']._serialized_start=113
  _globals['_CAMSTREAMPORT']._serialized_end=142
  _globals['_GPSCOORDINATES']._serialized_start=144
  _globals['_GPSCOORDINATES']._serialized_end=197
  _globals['_PROCESSORDATA']._serialized_start=199
  _globals['_PROCESSORDATA']._serialized_end=230
  _globals['_BATTERYDATA']._serialized_start=232
  _globals['_BATTERYDATA']._serialized_end=265
  _globals['_GENERALINFORMATIONDATA']._serialized_start=267
  _globals['_GENERALINFORMATIONDATA']._serialized_end=305
  _globals['_COMMANDSSERVICE']._serialized_start=308
  _globals['_COMMANDSSERVICE']._serialized_end=711
# @@protoc_insertion_point(module_scope)
